### ISSUE TITLE
Game Engine in C++ Modularized

### ISSUE THREAD

**Issue by edogdu** [edogdu/RAM_Cyber_Defenders#20]

**Comment by Luk-Er4** [comment]
Compared to the previous C++ script, I could improve readability by modulizing the function that calls the card information. 

![image](https://github.com/edogdu/RAM_Cyber_Defenders/assets/102909145/2468e1ff-ddef-4231-8e10-d49c1e0bdb4c)

This is the picture of the callTheCardInfos function. There are problems with this code, first of all, it is hard to read, and if there were any updates with card information, it would be hard to make changes. By performing the modulization of this code, I could solve both of the problems.

![image](https://github.com/edogdu/RAM_Cyber_Defenders/assets/102909145/47db676f-3d83-4ed3-816d-6ecab5f1f035)
![image](https://github.com/edogdu/RAM_Cyber_Defenders/assets/102909145/f45f3e18-1a29-43ff-83f2-9376e6570a76)

It took extra work to find the logic to handle this issue, but in the future, when it comes to expanding or updating this code, it pays off.

**Comment by LightTheBlues** [comment]
will not fix
