### ISSUE TITLE
Have scores be actively shown throughout the game

### ISSUE THREAD

**Issue by Luk-Er4** [edogdu/RAM_Cyber_Defenders#47]
We need a UI showing the points AI and the player earned.

**Comment by locada1** [comment]
The scoreboard that would only show at the end of the match has been made to appear behind the AI player and will display the current score throughout the game. It will also change colors depending on if the scores are tied, or one player is one point or two points above the other's score.

![Screenshot (334)](https://github.com/edogdu/RAM_Cyber_Defenders/assets/145424979/424303e5-6321-421c-80c4-629abf6d5bae)
![Screenshot (331)](https://github.com/edogdu/RAM_Cyber_Defenders/assets/145424979/9d719d5a-1c8e-47d3-80ae-7383f8b084f7)
![Screenshot (336)](https://github.com/edogdu/RAM_Cyber_Defenders/assets/145424979/b4da9eed-8939-4250-be99-81227f06bf4c)
