### ISSUE TITLE
Update AI animations

### ISSUE THREAD

**Issue by Luk-Er4** [edogdu/RAM_Cyber_Defenders#63]

**Comment by locada1** [comment]
I've been working on making new animations for the bot to replace the only one that was being used. So far, I've worked on an animation for the bot to draw a card from the deck and an animation to place a blue card on a spot in the middle of the blue assets row. I'm planning to try to make separate animations for placing cards in different parts of the board.

Below are what I have for these animations so far. The blue card that appears in the bot's hand is currently just a card attached to the actual model that I'm using for testing purposes.

The first animation would link to the second one.

(Bot drawing a card from the deck)
![Draw Card Animation - Made with Clipchamp](https://github.com/user-attachments/assets/f7c98f5c-53b1-4ec4-bcdb-af954af6bb2d)


   (Bot placing a blue card in the middle)
![Play Card Animation1 - Made with Clipchamp](https://github.com/user-attachments/assets/b55a1383-0471-49c7-8321-2afe7ac695dc)

**Comment by locada1** [comment]
New Animations have been made for the AI. The AI model should have an animation for each card position and actions the AI can make. 

The animations have all been wired up in the Animator tab in Unity, but the code hasn't been edited to change which chain of animations the AI will do.

![CS4091 Beta 1 2 - SecondRerrangement - Windows, Mac, Linux - Unity 2022 3 22f1 _DX11_ 7_24_2024 5_23_55 PM](https://github.com/user-attachments/assets/f9ed17a6-37d9-48b3-aa75-4136a3218575)
[With these current parameters, when PickUp is activated, the flow of animations will go to... 
Sitting -> Draw Card -> Drew Blue -> Play Blue1 -> Sit Down -> Sitting ]

![Animation Flow Sample - Made with Clipchamp](https://github.com/user-attachments/assets/595301c4-1da2-459d-a6df-b8c5a7aa1cec)

Setting up these animation flows should just be a matter of changing the parameters in the Animator tab through the code, like the AIPlayer script does for the PickUp parameter.

![CS4091 Beta 1 2 - SecondRerrangement - Windows, Mac, Linux - Unity 2022 3 22f1 _DX11_ 7_24_2024 5_23_55 PM](https://github.com/user-attachments/assets/274b479f-71fe-4aa5-aa38-02748bf23c79)

For now, I'll explain the parameters below:

When PickUp is activated, it will start the 'Draw Card' animation, which branches to different animations.
PickUp should be de-active before the animations loop back to 'Sitting'

Color is what color the card the AI drew is. It will dictate which branch the animation flow will go to.
1 is _blue_
2 is _green_
3 is _red_

Socket is the socket position of the eight card sockets on each row. The numbers should line up with the socket numbers in Unity.
0 is for the _discard pile_ if a card can't be played.
1 is for the 1st blue, green, or red socket (leftmost from the player's perspective)
2 is for the second socket
3 for the third
4 for the fourth
5, fifth
6, sixth
7, seventh
8 for the eighth (rightmost from the player's perspective)

Game End is to play some AI animations for when the game ends.
0 will not activate these animations for an ongoing game
1 will play an animation if the _AI won_ the match
2 will play an animation if the match ends in a _tie_
3 will play an animation if the _AI lost_ the match

**Comment by locada1** [comment]
I've coded some of the Animator parameters in the _Luis_branch_. 'PickUp' was already set, and I got 'Color' and 'Game End' set up in the AIPlayer script. I haven't changed around the timing of the card movement with the animations yet.

I wasn't able to set up the 'Socket' parameters yet. I thought since the AIPlayer script has the blueSockets in an array that get checked through a _foreach_ loop, I thought I could set it up to count the loop iterations or check the position in the array in the foreach loop to find the right 'Socket' parameter number, but neither of these seem to be working.

**Comment by locada1** [comment]
I got the code working now so the animations should be just about fully functional. I haven't changed the timing or card movement in this old build so the card just goes to position before the animations finish, but the animations should line up correctly to where the code tells the AI where it should play a card.

![Animations Wired - Made with Clipchamp](https://github.com/user-attachments/assets/67b085de-b18d-4296-883a-9dc6eb5ada19)

**Comment by locada1** [comment]
I have edited the code to move the card in sync to the animations. The card will move to the AI hand, then to it's position in the board at certain points in the animations.

![Card Movement - Made with Clipchamp](https://github.com/user-attachments/assets/b08efbf2-c0f6-4cdf-b0df-bdbfe1be2758)

I edited AIPlayer script and added new functions to move the card to the hands, to the board, and the discard pile. The animations themselves call these new functions through 'Animation Events', which are points in an animation where you can call a function in the script, so the card movements are currently tied to the animations.

![Screenshot (382)](https://github.com/user-attachments/assets/d0319b1a-b11f-4ab7-9f4f-e87e8b8fd587)
[ A bit after a second, the function 'PlayCard' is called by the animation event ]

This new change seems to be working properly, although a bit more polish may be needed.

**Comment by locada1** [comment]
I made changes to the AIPlayer script. I cleaned it up a bit, and changed it so the AI's card follows the hand movement better, as well as make the card rotate accordingly, while returning to its proper rotation once it moves to the board.

![Card Movement Improvement - Made with Clipchamp](https://github.com/user-attachments/assets/351b40b5-2ffd-498f-b18d-320737ba6b60)

**Comment by locada1** [comment]
Made some small changes to AIPlayer script. I disabled the dialogue script calls and implemented a fix for the null Reference error logs being repeatedly thrown by Unity. Now the only error logs in this build _should_ mostly be the ones intentionally thrown by the code to announce whose card it is, what the AI is trying to do, and who won the match.

**Comment by locada1** [comment]
Made a few more simple animations for the AI. These animations will play when the player doesn't play their card for enough time.
After three of the idle animations, it will switch to a "distracted" animation that will play instead of the 'sitting' animation.

![Distracted 1 - Made with Clipchamp (1)](https://github.com/user-attachments/assets/333b8e94-2e87-462a-8e7e-a0e687aa4458)
[ After about ten seconds, the first idle animation plays ]

![Distracted 2 - Made with Clipchamp](https://github.com/user-attachments/assets/2b915008-5993-49ba-8857-7fc598fc040c)
[ After enough time (after three idle animations) , the AI will switch to a "distracted" animation ]
