### ISSUE TITLE
Implementing renewed icons into the game

### ISSUE THREAD

**Issue by Luk-Er4** [edogdu/RAM_Cyber_Defenders#69]
Continuation of https://github.com/edogdu/RAM_Cyber_Defenders/issues/55

**Comment by Luk-Er4** [comment]
Renewed icons are in "RenewPopups" folder. 

-Regular 8 icons-
![image](https://github.com/user-attachments/assets/e6e17f86-dcd1-44f9-9b9e-3c13d8df308f)

-Special 4 icons(optional)-
![image](https://github.com/user-attachments/assets/790660fe-9c56-48d5-ae97-d90959d9d707)

There are icon samples in the "PopUpScene". 

The blue icons behind the green ones are designed for the special icons when the blue icon meets the green one. 

You can ignore the special icons if you think it might take too long time to implement all of them.

-Picture of "PopUpScene"-
![image](https://github.com/user-attachments/assets/ab3af5c2-31fd-4814-ae10-eb78e150679a)

**Comment by locada1** [comment]
I've added and implemented the renewed card icons, as well as the special icons. They seem to be fully functioning.

![Screenshot (401)](https://github.com/user-attachments/assets/e2d1ccb6-948d-486e-a95b-3f23b1a68423)

![Screenshot (403)](https://github.com/user-attachments/assets/a8cabfdd-ecc4-4272-8fe0-958417d2feb9)

![Screenshot (404)](https://github.com/user-attachments/assets/3c14b14b-8168-48c1-be02-b6ed60501def)

![Screenshot (406)](https://github.com/user-attachments/assets/32a2ec92-88d7-43e0-99b6-7040618d4239)

Note: Some of the renewed icon models seem to have collision, but it doesn't seem like it will cause issues.
